### ISSUE TITLE
AstroPyVO

### ISSUE THREAD

**Issue by astrograzl** [mkocka/galaxytea#17]
# AstroPyVO

_Workshop s tutoriály o AstroPy a Virtuální observatoři._

![Code writer](https://bitbucket.org/ulalume/astropyvo/wiki/artwork/640kB.jpg)

U příležitosti vydání [Astropy](http://www.astropy.org) ve verzi 1.0, bychom si rádi uspořádali přátelský seminář, k seznámení s možnostmi tohoto klíčového balíku programového kódu sloužícího k jednoduchému řešení praktických problémů moderní astrofyziky.

Seminář je určen všem zájemcům o virtuální astronomii. Naším skromným cílem je předvést jak řešit letité problémy novodobými postupy. Bez použití myši a pomocí moderního programovacího jazyka **Python**.
## Kde

Jako nejvhodnější místo pro setkání se nám jeví [Hvězdárna ve Vyškově](http://cs.wikipedia.org/wiki/Hv%C4%9Bzd%C3%A1rna_Vy%C5%A1kov), nacházející se uprostřed Dinoparku, jež je součástí ZOO-logické zahrady.
## Kdy

Termín konání akce o víkendu **24.--26. dubna 2015** byl demokraticky vybrán v issue [#1](https://bitbucket.org/ulalume/astropyvo/issue/1/term-n).
## Co

Ke konkrétní náplni demonstrovaných tutoriálů se můžete vyjadřovat v issue [#2](https://bitbucket.org/ulalume/astropyvo/issue/2/obsah).
## Jak

Máte-li zájem se zůčastnit, nebojte se vstoupit do virtuální místnosti [**AstroPyVO**](https://www.hipchat.com/gwSc32DrD) a hlasitě se ozvat. Pro další informace sledujte změny v tomto repozitáři a jeho Wiki sekci.

**Comment by mkocka** [comment]
;( ja som v tedy v prahe pravdepodobne ale este dam vediet ci naozaj

chces po mne aby som nieco povedal ? pripravil si ?

M

2015-04-13 13:23 GMT+02:00 Zdeněk Janák notifications@github.com:

**Comment by astrograzl** [comment]
Zdar, kdybys tam byl a chtělo by se ti, bylo by to fajn. Moje představa 
je ukázat jak vyřešit nějaký konkrétní problém spojený s praktickou 
astronomií.

A kdyby se vyjádřili i ostatní čajíčkáři...

Dne 13.4.2015 v 13:38 Matus Kocka napsal(a):

> ;( ja som v tedy v prahe pravdepodobne ale este dam vediet ci naozaj
> 
> chces po mne aby som nieco povedal ? pripravil si ?
> 
> M
> 
> 2015-04-13 13:23 GMT+02:00 Zdeněk Janák notifications@github.com:
> 
> > AstroPyVO
> > 
> > _Workshop s tutoriály o AstroPy a Virtuální observatoři._
> > 
> > [image: Code writer]
> > 
> > https://camo.githubusercontent.com/ec03391249eedc298b8e1c5820587c5c5373b75a/68747470733a2f2f6269746275636b65742e6f72672f756c616c756d652f617374726f7079766f2f77696b692f617274776f726b2f3634306b422e6a7067
> > 
> > U příležitosti vydání Astropy http://www.astropy.org ve verzi 1.0,
> > bychom si rádi uspořádali přátelský seminář, k seznámení s možnostmi
> > tohoto
> > klíčového balíku programového kódu sloužícího k jednoduchému řešení
> > praktických problémů moderní astrofyziky.
> > 
> > Seminář je určen všem zájemcům o virtuální astronomii. Naším skromným
> > cílem je předvést jak řešit letité problémy novodobými postupy. Bez
> > použití
> > myši a pomocí moderního programovacího jazyka _Python_.
> > Kde
> > 
> > Jako nejvhodnější místo pro setkání se nám jeví Hvězdárna ve Vyškově
> > http://cs.wikipedia.org/wiki/Hv%C4%9Bzd%C3%A1rna_Vy%C5%A1kov,
> > nacházející se uprostřed Dinoparku, jež je součástí ZOO-logické zahrady.
> > Kdy
> > 
> > Termín konání akce o víkendu _24.--26. dubna 2015_ byl demokraticky
> > vybrán v issue #1
> > https://bitbucket.org/ulalume/astropyvo/issue/1/term-n
> > .
> > Co
> > 
> > Ke konkrétní náplni demonstrovaných tutoriálů se můžete vyjadřovat v
> > issue
> > #2 https://bitbucket.org/ulalume/astropyvo/issue/2/obsah.
> > Jak
> > 
> > Máte-li zájem se zůčastnit, nebojte se vstoupit do virtuální místnosti
> > _AstroPyVO_ https://www.hipchat.com/gwSc32DrD a hlasitě se ozvat. Pro
> > další informace sledujte změny v tomto repozitáři a jeho Wiki sekci.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/mkocka/galaxytea/issues/17.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mkocka/galaxytea/issues/17#issuecomment-92322395.

## 

Zdeněk Janák janak@astronomie.cz
http://janak.astronomie.cz/

**Comment by mkocka** [comment]
Ook tak ja si nieco rozmyslim a zajtra mozeme dat o tom rec

2015-04-13 13:43 GMT+02:00 Zdeněk Janák notifications@github.com:
